### PR TITLE
Migrate to hammer-cli plugin

### PR DESCRIPTION
**Pull request by maria**
## Need

``` gherkin
As a developer
I want to migrate the Foregit library as a hammer-cli plugin
So that I can create a standard tool between Foreman and Git
Which is easy to use and integrate 
```
## Deliverables
- A hammer-cli plugin, which has the `pull` and `push` command to sync Foreman and Git
- A configurable plugin 
#### Prerequisites
- [hammer-cli](https://github.com/theforeman/hammer-cli/blob/master/doc/writing_a_plugin.md)
- First try https://github.com/marianitadn/foregit/pull/12/files
- Plugin example https://github.com/theforeman/hammer-cli-foreman
#### TODO
- [x] Add hammer-cli as dependency
- [x] Rename library  - hammer_foregit
- [ ] Remove settings configuration, use the one provided by hammer
- [ ] Update commands, use the hammer Command class to add new commands

### CODE REVIEW

**Comment by maria** [comment]
I still get this error

```
[ INFO 2014-07-16 15:27:26 Init] Initialization of Hammer CLI (0.1.1) has started...
[DEBUG 2014-07-16 15:27:26 Init] Running at ruby 2.0.0-p481
[ INFO 2014-07-16 15:27:26 Init] Configuration from the file /etc/hammer/cli.modules.d/foregit.yml has been loaded
[ INFO 2014-07-16 15:27:26 Init] Configuration from the file /etc/hammer/cli.modules.d/foreman.yml has been loaded
[ERROR 2014-07-16 15:27:26 Modules] Error while loading module hammer_cli_foregit
[ERROR 2014-07-16 15:27:26 Modules] <LoadError> cannot load such file -- foregit
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli_foregit-0.1/lib/hammer_cli_foregit/file_manager.rb:4:in `<top (required)>'
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli_foregit-0.1/lib/hammer_cli_foregit.rb:3:in `<module:Foregit>'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli_foregit-0.1/lib/hammer_cli_foregit.rb:1:in `<top (required)>'
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/lib/hammer_cli/modules.rb:60:in `require_module'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/lib/hammer_cli/modules.rb:39:in `load!'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/lib/hammer_cli/modules.rb:54:in `load'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/lib/hammer_cli/modules.rb:65:in `block in load_all'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/lib/hammer_cli/modules.rb:64:in `each'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/lib/hammer_cli/modules.rb:64:in `load_all'
        /usr/local/rvm/gems/ruby-2.0.0-p481/gems/hammer_cli-0.1.1/bin/hammer:87:in `<top (required)>'
        /usr/local/rvm/gems/ruby-2.0.0-p481/bin/hammer:23:in `load'
        /usr/local/rvm/gems/ruby-2.0.0-p481/bin/hammer:23:in `<main>'
        /usr/local/rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
        /usr/local/rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
[ERROR 2014-07-16 15:27:26 Modules] Error while loading module hammer_cli_foreman
```

and I don't know how to fix it.

**Comment by iNecas** [comment]
You would need to `require 'hammer_cli_foregit'` instead of `require 'foregit'`, on the other hand, the conventions would suggest to call the main namespace 'HammerCLIForegit', so I wonder, if we need to rename it to `hammer_cli_foregit` in the first place. I liked the `Foregit` better as it's shorter. I can't remember the hammer would enforce the naming.

**Comment by maria** [comment]
It looks for `hammer_cli_<module_name>` where module name is defined in `hammer/cli.modules.d/foregit.yml`, as far as I read/tried.

**Comment by iNecas** [comment]
Ah, right. So what about defining the `hammer_cli_foregit.rb`, but inside it, just require the 'foregit' and keep the logic in the foregit.rb and the Foregit module, having the hammer_cli_foregit.rb just as an entry point that hammer can load?

**Comment by maria** [comment]
Ok, we can do that :). But do you think it may become confusing for others?

**Comment by iNecas** [comment]
It came though my mind as well, but it doesn't seem to me as such a big deal, and it gives us shorter namespaces, which is alwasy good :). The difference between the hammer_cli_foreman plugin and this is that there will be more business logic, than just translating the commands to the API calls. I will leave the final decision on you

**Comment by maria** [comment]
I will change the naming as you said, and I will try to keep the hammer-cli related files separated by the files related with the foregit logic.

**Comment by iNecas** [comment]
Sounds good

**Pull request closed without merging**
