### PR TITLE
Migrate to hammer-cli

### PR DESCRIPTION
**Pull request by maria**
## Need

``` gherkin
As a developer
I want to migrate the Foregit library as a hammer-cli plugin
So that I can create a standard tool between Foreman and Git
Which is easy to use and integrate 
```
## Deliverables
- A hammer-cli plugin, which has the `pull` and `push` command to sync Foreman and Git
- A configurable plugin 
#### Prerequisites
- [hammer-cli](https://github.com/theforeman/hammer-cli/blob/master/doc/writing_a_plugin.md)
- First try https://github.com/marianitadn/foregit/pull/12/files
- Plugin example https://github.com/theforeman/hammer-cli-foreman
#### TODO
- [x] Add hammer-cli as dependency
- [x] Rename library  - hammer_foregit
- [x] Remove settings configuration, use the one provided by hammer
- [x] Update commands, use the hammer Command class to add new commands
- [x] Fix https://github.com/marianitadn/foregit/issues/14#issuecomment-49555912
- [x] Fix tests

### CODE REVIEW

**Comment by maria** [comment]
No errors so far, but the command is not in the list

**Comment by maria** [comment]
working - now I can continue the migration

**Comment by maria** [comment]
@iNecas this is done. I'm going to fix https://github.com/marianitadn/foregit/issues/15 and think about how to detect a change type based on the commits diff.

**Comment by iNecas** [comment]
Looks good from the code perspective. One thing, that is not related directly to moving to the hammer: It's a good practice for the gems to wrap all of their constants into a module, to avoid conflicts, between gems.  So ideally, the FileManager, GitManager and TalkCommands would be nested under the Foregit module.

**Comment by maria** [comment]
Yes, and I said I will do that. I will add them under Foregit module and after that I will merge it. Thanks

**Comment by iNecas** [comment]
Let's get this in then :)

**Pull request merged**
